window.__FITCUE_VIDEOS__ = [
  {
    "id": 1,
    "platform": "YouTube",
    "author": "Chloe Ting",
    "title": "10 Min Abs Workout — Get Abs in 2 Weeks",
    "url": "https://www.youtube.com/watch?v=2pLT-olgUJs",
    "duration": 10,
    "type": "Strength",
    "target": "Core",
    "space": "<2",
    "equipment": "Bodyweight",
    "noise": "Low",
    "difficulty": "Intermediate",
    "tags": [
      "No jumping"
    ],
    "quality": 4,
    "videoId": "2pLT-olgUJs",
    "thumbnail": "https://img.youtube.com/vi/2pLT-olgUJs/mqdefault.jpg"
  },
  {
    "id": 2,
    "platform": "YouTube",
    "author": "Pamela Reif",
    "title": "10 MIN BEGINNER AB WORKOUT — no equipment",
    "url": "https://www.youtube.com/watch?v=1f8yoFFdkcY",
    "duration": 10,
    "type": "Strength",
    "target": "Core",
    "space": "<2",
    "equipment": "Yoga mat",
    "noise": "Low",
    "difficulty": "Beginner",
    "tags": [
      "Beginner-friendly"
    ],
    "quality": 5,
    "videoId": "1f8yoFFdkcY",
    "thumbnail": "https://img.youtube.com/vi/1f8yoFFdkcY/mqdefault.jpg"
  },
  {
    "id": 3,
    "platform": "YouTube",
    "author": "MadFit",
    "title": "10 Min APARTMENT FRIENDLY Full Body Workout",
    "url": "https://www.youtube.com/watch?v=LvV7K_i7aDQ",
    "duration": 10,
    "type": "Mixed",
    "target": "Full body",
    "space": "<2",
    "equipment": "Bodyweight",
    "noise": "Silent",
    "difficulty": "Beginner",
    "tags": [
      "No jumping",
      "Low noise",
      "Beginner-friendly"
    ],
    "quality": 5,
    "videoId": "LvV7K_i7aDQ",
    "thumbnail": "https://img.youtube.com/vi/LvV7K_i7aDQ/mqdefault.jpg"
  },
  {
    "id": 4,
    "platform": "YouTube",
    "author": "Caroline Girvan",
    "title": "20 Min DUMBBELL UPPER BODY Workout at Home",
    "url": "https://www.youtube.com/watch?v=JZPzynsdYCE",
    "duration": 20,
    "type": "Strength",
    "target": "Upper body",
    "space": "2-5",
    "equipment": "Dumbbells",
    "noise": "Low",
    "difficulty": "Advanced",
    "tags": [],
    "quality": 5,
    "videoId": "JZPzynsdYCE",
    "thumbnail": "https://img.youtube.com/vi/JZPzynsdYCE/mqdefault.jpg"
  },
  {
    "id": 5,
    "platform": "YouTube",
    "author": "Jeff Nippard",
    "title": "The Smartest Push Day (Chest, Shoulders, Triceps)",
    "url": "https://www.youtube.com/watch?v=LwHoNk-sjgs",
    "duration": 25,
    "type": "Strength",
    "target": "Upper body",
    "space": "5+",
    "equipment": "Gym equipment",
    "noise": "Medium",
    "difficulty": "Advanced",
    "tags": [],
    "quality": 5,
    "videoId": "LwHoNk-sjgs",
    "thumbnail": "https://img.youtube.com/vi/LwHoNk-sjgs/mqdefault.jpg"
  },
  {
    "id": 6,
    "platform": "YouTube",
    "author": "Athlean-X",
    "title": "The PERFECT Home Chest Workout — No Equipment",
    "url": "https://www.youtube.com/watch?v=rxEMKXW2Wqs",
    "duration": 12,
    "type": "Strength",
    "target": "Chest",
    "space": "2-5",
    "equipment": "Bodyweight",
    "noise": "Medium",
    "difficulty": "Intermediate",
    "tags": [],
    "quality": 5,
    "videoId": "rxEMKXW2Wqs",
    "thumbnail": "https://img.youtube.com/vi/rxEMKXW2Wqs/mqdefault.jpg"
  },
  {
    "id": 7,
    "platform": "YouTube",
    "author": "Chris Heria",
    "title": "15 Min HOME BACK WORKOUT — No Equipment",
    "url": "https://www.youtube.com/watch?v=QqZV3JEoOlc",
    "duration": 15,
    "type": "Strength",
    "target": "Back",
    "space": "2-5",
    "equipment": "Bodyweight",
    "noise": "Low",
    "difficulty": "Intermediate",
    "tags": [],
    "quality": 4,
    "videoId": "QqZV3JEoOlc",
    "thumbnail": "https://img.youtube.com/vi/QqZV3JEoOlc/mqdefault.jpg"
  },
  {
    "id": 8,
    "platform": "YouTube",
    "author": "Heather Robertson",
    "title": "20 Min Full Body HIIT — No Equipment, No Repeat",
    "url": "https://www.youtube.com/watch?v=ZH-Fi8H0-Kg",
    "duration": 20,
    "type": "HIIT",
    "target": "Full body",
    "space": "2-5",
    "equipment": "Bodyweight",
    "noise": "High",
    "difficulty": "Intermediate",
    "tags": [],
    "quality": 4,
    "videoId": "ZH-Fi8H0-Kg",
    "thumbnail": "https://img.youtube.com/vi/ZH-Fi8H0-Kg/mqdefault.jpg"
  },
  {
    "id": 9,
    "platform": "YouTube",
    "author": "Growingannanas",
    "title": "30 MIN FULL BODY HIIT — No Jumping, Low Impact",
    "url": "https://www.youtube.com/watch?v=6g9myTPcb7Y",
    "duration": 30,
    "type": "HIIT",
    "target": "Full body",
    "space": "2-5",
    "equipment": "Bodyweight",
    "noise": "Medium",
    "difficulty": "Intermediate",
    "tags": [
      "No jumping",
      "Low noise"
    ],
    "quality": 5,
    "videoId": "6g9myTPcb7Y",
    "thumbnail": "https://img.youtube.com/vi/6g9myTPcb7Y/mqdefault.jpg"
  },
  {
    "id": 10,
    "platform": "YouTube",
    "author": "Yoga with Adriene",
    "title": "20 Min Yoga for Complete Beginners",
    "url": "https://www.youtube.com/watch?v=v7AYKMP6rOE",
    "duration": 20,
    "type": "Mobility",
    "target": "Full body",
    "space": "2-5",
    "equipment": "Yoga mat",
    "noise": "Silent",
    "difficulty": "Beginner",
    "tags": [
      "Beginner-friendly"
    ],
    "quality": 5,
    "videoId": "v7AYKMP6rOE",
    "thumbnail": "https://img.youtube.com/vi/v7AYKMP6rOE/mqdefault.jpg"
  },
  {
    "id": 11,
    "platform": "YouTube",
    "author": "Move with Nicole",
    "title": "20 MIN FULL BODY PILATES — No Equipment",
    "url": "https://www.youtube.com/watch?v=XoqDtdggZ3I",
    "duration": 20,
    "type": "Mobility",
    "target": "Full body",
    "space": "2-5",
    "equipment": "Yoga mat",
    "noise": "Silent",
    "difficulty": "Intermediate",
    "tags": [],
    "quality": 5,
    "videoId": "XoqDtdggZ3I",
    "thumbnail": "https://img.youtube.com/vi/XoqDtdggZ3I/mqdefault.jpg"
  },
  {
    "id": 12,
    "platform": "YouTube",
    "author": "Body Project",
    "title": "20 Min Low Impact Cardio — All Standing, No Jumping",
    "url": "https://www.youtube.com/watch?v=x3aogIZfVUI",
    "duration": 20,
    "type": "Cardio",
    "target": "Full body",
    "space": "2-5",
    "equipment": "Bodyweight",
    "noise": "Low",
    "difficulty": "Beginner",
    "tags": [
      "Beginner-friendly",
      "No jumping",
      "Knee / back friendly"
    ],
    "quality": 4,
    "videoId": "x3aogIZfVUI",
    "thumbnail": "https://img.youtube.com/vi/x3aogIZfVUI/mqdefault.jpg"
  },
  {
    "id": 13,
    "platform": "YouTube",
    "author": "HASfit",
    "title": "20 Min Low Impact HIIT for Beginners — Knee Friendly",
    "url": "https://www.youtube.com/watch?v=bkhgiktiloQ",
    "duration": 20,
    "type": "HIIT",
    "target": "Full body",
    "space": "2-5",
    "equipment": "Bodyweight",
    "noise": "Low",
    "difficulty": "Beginner",
    "tags": [
      "Beginner-friendly",
      "Knee / back friendly",
      "No jumping"
    ],
    "quality": 4,
    "videoId": "bkhgiktiloQ",
    "thumbnail": "https://img.youtube.com/vi/bkhgiktiloQ/mqdefault.jpg"
  },
  {
    "id": 14,
    "platform": "YouTube",
    "author": "Joe Wicks",
    "title": "20 Minute Full Body Home Workout",
    "url": "https://www.youtube.com/watch?v=Og_f0_QO_Ko",
    "duration": 20,
    "type": "Mixed",
    "target": "Full body",
    "space": "2-5",
    "equipment": "Bodyweight",
    "noise": "Medium",
    "difficulty": "Intermediate",
    "tags": [],
    "quality": 4,
    "videoId": "Og_f0_QO_Ko",
    "thumbnail": "https://img.youtube.com/vi/Og_f0_QO_Ko/mqdefault.jpg"
  },
  {
    "id": 15,
    "platform": "YouTube",
    "author": "Fitness Blender",
    "title": "15 Min HIIT Cardio — Apartment Friendly",
    "url": "https://www.youtube.com/watch?v=WUg5dP6W0cw",
    "duration": 15,
    "type": "HIIT",
    "target": "Full body",
    "space": "<2",
    "equipment": "Bodyweight",
    "noise": "Low",
    "difficulty": "Intermediate",
    "tags": [
      "Low noise",
      "No jumping"
    ],
    "quality": 4,
    "videoId": "WUg5dP6W0cw",
    "thumbnail": "https://img.youtube.com/vi/WUg5dP6W0cw/mqdefault.jpg"
  },
  {
    "id": 16,
    "platform": "YouTube",
    "author": "Pamela Reif",
    "title": "15 MIN BOOTY WORKOUT — No Equipment, No Jumping",
    "url": "https://www.youtube.com/watch?v=p-uUnrCdhR8",
    "duration": 15,
    "type": "Strength",
    "target": "Legs / glutes",
    "space": "2-5",
    "equipment": "Yoga mat",
    "noise": "Low",
    "difficulty": "Intermediate",
    "tags": [
      "No jumping"
    ],
    "quality": 5,
    "videoId": "p-uUnrCdhR8",
    "thumbnail": "https://img.youtube.com/vi/p-uUnrCdhR8/mqdefault.jpg"
  },
  {
    "id": 17,
    "platform": "YouTube",
    "author": "Caroline Girvan",
    "title": "30 Min DUMBBELL LEG DAY — Glutes, Quads, Hamstrings",
    "url": "https://www.youtube.com/watch?v=UEWEYeJGkLM",
    "duration": 30,
    "type": "Strength",
    "target": "Legs / glutes",
    "space": "2-5",
    "equipment": "Dumbbells",
    "noise": "Medium",
    "difficulty": "Advanced",
    "tags": [],
    "quality": 5,
    "videoId": "UEWEYeJGkLM",
    "thumbnail": "https://img.youtube.com/vi/UEWEYeJGkLM/mqdefault.jpg"
  },
  {
    "id": 18,
    "platform": "YouTube",
    "author": "Blogilates",
    "title": "10 MIN ARMS WORKOUT — Toned Arms",
    "url": "https://www.youtube.com/watch?v=CaQO5Fd4PEA",
    "duration": 10,
    "type": "Strength",
    "target": "Arms",
    "space": "<2",
    "equipment": "Bodyweight",
    "noise": "Silent",
    "difficulty": "Beginner",
    "tags": [
      "Beginner-friendly"
    ],
    "quality": 4,
    "videoId": "CaQO5Fd4PEA",
    "thumbnail": "https://img.youtube.com/vi/CaQO5Fd4PEA/mqdefault.jpg"
  },
  {
    "id": 19,
    "platform": "YouTube",
    "author": "Sydney Cummings",
    "title": "30 Min Full Body STRENGTH + CARDIO — Dumbbells",
    "url": "https://www.youtube.com/watch?v=jO1Yb0T4DuQ",
    "duration": 30,
    "type": "Mixed",
    "target": "Full body",
    "space": "2-5",
    "equipment": "Dumbbells",
    "noise": "Medium",
    "difficulty": "Intermediate",
    "tags": [],
    "quality": 4,
    "videoId": "jO1Yb0T4DuQ",
    "thumbnail": "https://img.youtube.com/vi/jO1Yb0T4DuQ/mqdefault.jpg"
  },
  {
    "id": 20,
    "platform": "YouTube",
    "author": "Chris Heria",
    "title": "10 Min SHOULDER WORKOUT at Home — Dumbbells",
    "url": "https://www.youtube.com/watch?v=g5oQZmk7xMc",
    "duration": 10,
    "type": "Strength",
    "target": "Shoulders",
    "space": "<2",
    "equipment": "Dumbbells",
    "noise": "Low",
    "difficulty": "Intermediate",
    "tags": [],
    "quality": 4,
    "videoId": "g5oQZmk7xMc",
    "thumbnail": "https://img.youtube.com/vi/g5oQZmk7xMc/mqdefault.jpg"
  },
  {
    "id": 21,
    "platform": "YouTube",
    "author": "MadFit",
    "title": "15 MIN DUMBBELL BACK WORKOUT — Apartment Friendly",
    "url": "https://www.youtube.com/watch?v=mHyScGuLIzU",
    "duration": 15,
    "type": "Strength",
    "target": "Back",
    "space": "2-5",
    "equipment": "Dumbbells",
    "noise": "Low",
    "difficulty": "Intermediate",
    "tags": [
      "Low noise"
    ],
    "quality": 4,
    "videoId": "mHyScGuLIzU",
    "thumbnail": "https://img.youtube.com/vi/mHyScGuLIzU/mqdefault.jpg"
  },
  {
    "id": 22,
    "platform": "YouTube",
    "author": "Pregnancy & Postpartum TV",
    "title": "15 Min Postpartum Core Recovery — Safe for Diastasis Recti",
    "url": "https://www.youtube.com/watch?v=C-7TU-YypsA",
    "duration": 15,
    "type": "Strength",
    "target": "Core",
    "space": "2-5",
    "equipment": "Yoga mat",
    "noise": "Silent",
    "difficulty": "Beginner",
    "tags": [
      "Postpartum-friendly",
      "Knee / back friendly"
    ],
    "quality": 5,
    "videoId": "C-7TU-YypsA",
    "thumbnail": "https://img.youtube.com/vi/C-7TU-YypsA/mqdefault.jpg"
  },
  {
    "id": 23,
    "platform": "YouTube",
    "author": "BodyFit by Amy",
    "title": "20 Min Postnatal Full Body Workout — Baby Friendly",
    "url": "https://www.youtube.com/watch?v=UxstRqRaIPs",
    "duration": 20,
    "type": "Mixed",
    "target": "Full body",
    "space": "2-5",
    "equipment": "Yoga mat",
    "noise": "Low",
    "difficulty": "Beginner",
    "tags": [
      "Postpartum-friendly",
      "No jumping"
    ],
    "quality": 4,
    "videoId": "UxstRqRaIPs",
    "thumbnail": "https://img.youtube.com/vi/UxstRqRaIPs/mqdefault.jpg"
  },
  {
    "id": 24,
    "platform": "YouTube",
    "author": "GlowBodyPT",
    "title": "25 Min Postpartum HIIT — Low Impact, Diastasis Safe",
    "url": "https://www.youtube.com/watch?v=RRdAVeBYwTw",
    "duration": 25,
    "type": "HIIT",
    "target": "Full body",
    "space": "2-5",
    "equipment": "Resistance band",
    "noise": "Low",
    "difficulty": "Intermediate",
    "tags": [
      "Postpartum-friendly",
      "No jumping",
      "Low noise"
    ],
    "quality": 4,
    "videoId": "RRdAVeBYwTw",
    "thumbnail": "https://img.youtube.com/vi/RRdAVeBYwTw/mqdefault.jpg"
  },
  {
    "id": 25,
    "platform": "YouTube",
    "author": "HASfit",
    "title": "30 Min Strength Training for Seniors — All Seated Option",
    "url": "https://www.youtube.com/watch?v=UKfNi0IIndA",
    "duration": 30,
    "type": "Strength",
    "target": "Full body",
    "space": "2-5",
    "equipment": "Dumbbells",
    "noise": "Silent",
    "difficulty": "Beginner",
    "tags": [
      "Knee / back friendly"
    ],
    "quality": 4,
    "videoId": "UKfNi0IIndA",
    "thumbnail": "https://img.youtube.com/vi/UKfNi0IIndA/mqdefault.jpg"
  },
  {
    "id": 26,
    "platform": "YouTube",
    "author": "SilverSneakers",
    "title": "15 Min Chair Workout for Seniors — Full Body",
    "url": "https://www.youtube.com/watch?v=HwES4OSc9H8",
    "duration": 15,
    "type": "Mixed",
    "target": "Full body",
    "space": "<2",
    "equipment": "Bodyweight",
    "noise": "Silent",
    "difficulty": "Beginner",
    "tags": [
      "Knee / back friendly"
    ],
    "quality": 4,
    "videoId": "HwES4OSc9H8",
    "thumbnail": "https://img.youtube.com/vi/HwES4OSc9H8/mqdefault.jpg"
  },
  {
    "id": 27,
    "platform": "YouTube",
    "author": "Joe Wicks",
    "title": "10 Min Kids Workout — Fun HIIT for Families",
    "url": "https://www.youtube.com/watch?v=kHukIPOIrnk",
    "duration": 10,
    "type": "HIIT",
    "target": "Full body",
    "space": "2-5",
    "equipment": "Bodyweight",
    "noise": "Medium",
    "difficulty": "Beginner",
    "tags": [
      "Beginner-friendly"
    ],
    "quality": 4,
    "videoId": "kHukIPOIrnk",
    "thumbnail": "https://img.youtube.com/vi/kHukIPOIrnk/mqdefault.jpg"
  },
  {
    "id": 28,
    "platform": "YouTube",
    "author": "Caroline Girvan",
    "title": "15 Min KETTLEBELL Full Body Workout",
    "url": "https://www.youtube.com/watch?v=VCcar3MA07w",
    "duration": 15,
    "type": "Strength",
    "target": "Full body",
    "space": "2-5",
    "equipment": "Kettlebell",
    "noise": "Medium",
    "difficulty": "Advanced",
    "tags": [],
    "quality": 5,
    "videoId": "VCcar3MA07w",
    "thumbnail": "https://img.youtube.com/vi/VCcar3MA07w/mqdefault.jpg"
  },
  {
    "id": 29,
    "platform": "YouTube",
    "author": "Heather Robertson",
    "title": "10 Min STANDING ABS — No Equipment, No Lying Down",
    "url": "https://www.youtube.com/watch?v=Qia2ZXEzyLw",
    "duration": 10,
    "type": "Strength",
    "target": "Core",
    "space": "<2",
    "equipment": "Bodyweight",
    "noise": "Low",
    "difficulty": "Intermediate",
    "tags": [
      "No jumping",
      "Low noise"
    ],
    "quality": 4,
    "videoId": "Qia2ZXEzyLw",
    "thumbnail": "https://img.youtube.com/vi/Qia2ZXEzyLw/mqdefault.jpg"
  },
  {
    "id": 30,
    "platform": "YouTube",
    "author": "Athlean-X",
    "title": "7 Min Home Shoulder Workout — Fix Your Posture",
    "url": "https://www.youtube.com/watch?v=YAUGMT0_PiE",
    "duration": 7,
    "type": "Strength",
    "target": "Shoulders",
    "space": "<2",
    "equipment": "Resistance band",
    "noise": "Silent",
    "difficulty": "Intermediate",
    "tags": [
      "Knee / back friendly"
    ],
    "quality": 5,
    "videoId": "YAUGMT0_PiE",
    "thumbnail": "https://img.youtube.com/vi/YAUGMT0_PiE/mqdefault.jpg"
  },
  {
    "id": 31,
    "platform": "YouTube",
    "author": "Yoga with Adriene",
    "title": "10 Min Yoga for Back Pain — Lower Back Relief",
    "url": "https://www.youtube.com/watch?v=XeXz8fIZDCE",
    "duration": 10,
    "type": "Mobility",
    "target": "Full body",
    "space": "2-5",
    "equipment": "Yoga mat",
    "noise": "Silent",
    "difficulty": "Beginner",
    "tags": [
      "Knee / back friendly",
      "Beginner-friendly"
    ],
    "quality": 5,
    "videoId": "XeXz8fIZDCE",
    "thumbnail": "https://img.youtube.com/vi/XeXz8fIZDCE/mqdefault.jpg"
  },
  {
    "id": 32,
    "platform": "YouTube",
    "author": "Move with Nicole",
    "title": "10 MIN MORNING PILATES — Wake Up & Stretch",
    "url": "https://www.youtube.com/watch?v=UxU8OCsNbYY",
    "duration": 10,
    "type": "Mobility",
    "target": "Full body",
    "space": "<2",
    "equipment": "Yoga mat",
    "noise": "Silent",
    "difficulty": "Beginner",
    "tags": [
      "Beginner-friendly",
      "No jumping"
    ],
    "quality": 5,
    "videoId": "UxU8OCsNbYY",
    "thumbnail": "https://img.youtube.com/vi/UxU8OCsNbYY/mqdefault.jpg"
  },
  {
    "id": 33,
    "platform": "YouTube",
    "author": "Chloe Ting",
    "title": "15 Min Full Body HIIT — No Equipment",
    "url": "https://www.youtube.com/watch?v=9rQ5wxssQss",
    "duration": 15,
    "type": "HIIT",
    "target": "Full body",
    "space": "2-5",
    "equipment": "Bodyweight",
    "noise": "High",
    "difficulty": "Intermediate",
    "tags": [],
    "quality": 4,
    "videoId": "9rQ5wxssQss",
    "thumbnail": "https://img.youtube.com/vi/9rQ5wxssQss/mqdefault.jpg"
  },
  {
    "id": 34,
    "platform": "YouTube",
    "author": "Growingannanas",
    "title": "30 MIN LEGS + BOOTY Workout with Resistance Bands",
    "url": "https://www.youtube.com/watch?v=6FCu_X_XqpQ",
    "duration": 30,
    "type": "Strength",
    "target": "Legs / glutes",
    "space": "2-5",
    "equipment": "Resistance band",
    "noise": "Low",
    "difficulty": "Intermediate",
    "tags": [],
    "quality": 4,
    "videoId": "6FCu_X_XqpQ",
    "thumbnail": "https://img.youtube.com/vi/6FCu_X_XqpQ/mqdefault.jpg"
  },
  {
    "id": 35,
    "platform": "YouTube",
    "author": "Jeff Nippard",
    "title": "15 Min Science-Based BAND ONLY Full Body Workout",
    "url": "https://www.youtube.com/watch?v=eMjyvIQbn9M",
    "duration": 15,
    "type": "Strength",
    "target": "Full body",
    "space": "2-5",
    "equipment": "Resistance band",
    "noise": "Low",
    "difficulty": "Intermediate",
    "tags": [
      "Low noise",
      "Hotel-friendly"
    ],
    "quality": 5,
    "videoId": "eMjyvIQbn9M",
    "thumbnail": "https://img.youtube.com/vi/eMjyvIQbn9M/mqdefault.jpg"
  },
  {
    "id": 36,
    "platform": "YouTube",
    "author": "Pamela Reif",
    "title": "10 MIN BOOTY BURN — Resistance Band, No Jumping",
    "url": "https://www.youtube.com/watch?v=lRFxt8BHxT0",
    "duration": 10,
    "type": "Strength",
    "target": "Legs / glutes",
    "space": "<2",
    "equipment": "Resistance band",
    "noise": "Low",
    "difficulty": "Intermediate",
    "tags": [
      "No jumping",
      "Low noise"
    ],
    "quality": 5,
    "videoId": "lRFxt8BHxT0",
    "thumbnail": "https://img.youtube.com/vi/lRFxt8BHxT0/mqdefault.jpg"
  },
  {
    "id": 37,
    "platform": "YouTube",
    "author": "MadFit",
    "title": "15 Min DORM ROOM WORKOUT — Super Small Space, No Noise",
    "url": "https://www.youtube.com/watch?v=9PCGvkXV-Bo",
    "duration": 15,
    "type": "Mixed",
    "target": "Full body",
    "space": "<2",
    "equipment": "Bodyweight",
    "noise": "Silent",
    "difficulty": "Beginner",
    "tags": [
      "Beginner-friendly",
      "Low noise",
      "Hotel-friendly"
    ],
    "quality": 5,
    "videoId": "9PCGvkXV-Bo",
    "thumbnail": "https://img.youtube.com/vi/9PCGvkXV-Bo/mqdefault.jpg"
  },
  {
    "id": 38,
    "platform": "YouTube",
    "author": "Chris Heria",
    "title": "20 Min FULL BODY Workout — Follow Along, No Equipment",
    "url": "https://www.youtube.com/watch?v=5KXZ9I2z1m4",
    "duration": 20,
    "type": "Mixed",
    "target": "Full body",
    "space": "2-5",
    "equipment": "Bodyweight",
    "noise": "Medium",
    "difficulty": "Intermediate",
    "tags": [],
    "quality": 4,
    "videoId": "5KXZ9I2z1m4",
    "thumbnail": "https://img.youtube.com/vi/5KXZ9I2z1m4/mqdefault.jpg"
  },
  {
    "id": 39,
    "platform": "YouTube",
    "author": "Blogilates",
    "title": "20 MIN FULL BODY PILATES — All Standing",
    "url": "https://www.youtube.com/watch?v=QPQ6a4P5qT8",
    "duration": 20,
    "type": "Mobility",
    "target": "Full body",
    "space": "<2",
    "equipment": "Bodyweight",
    "noise": "Silent",
    "difficulty": "Beginner",
    "tags": [
      "Beginner-friendly",
      "No jumping"
    ],
    "quality": 4,
    "videoId": "QPQ6a4P5qT8",
    "thumbnail": "https://img.youtube.com/vi/QPQ6a4P5qT8/mqdefault.jpg"
  },
  {
    "id": 40,
    "platform": "YouTube",
    "author": "Sydney Cummings",
    "title": "40 Min Total Body STRENGTH — Dumbbells + Bench",
    "url": "https://www.youtube.com/watch?v=WxT1_ZpJZHg",
    "duration": 40,
    "type": "Strength",
    "target": "Full body",
    "space": "5+",
    "equipment": "Gym equipment",
    "noise": "Medium",
    "difficulty": "Intermediate",
    "tags": [],
    "quality": 4,
    "videoId": "WxT1_ZpJZHg",
    "thumbnail": "https://img.youtube.com/vi/WxT1_ZpJZHg/mqdefault.jpg"
  },
  {
    "id": 41,
    "platform": "YouTube",
    "author": "Athlean-X",
    "title": "8 Min PERFECT Abs Workout — Science-Based",
    "url": "https://www.youtube.com/watch?v=N55JQubU1FE",
    "duration": 8,
    "type": "Strength",
    "target": "Core",
    "space": "2-5",
    "equipment": "Bodyweight",
    "noise": "Low",
    "difficulty": "Intermediate",
    "tags": [
      "Knee / back friendly"
    ],
    "quality": 5,
    "videoId": "N55JQubU1FE",
    "thumbnail": "https://img.youtube.com/vi/N55JQubU1FE/mqdefault.jpg"
  },
  {
    "id": 42,
    "platform": "YouTube",
    "author": "HASfit",
    "title": "20 Min Bad Knees — No Squats No Lunges Full Body",
    "url": "https://www.youtube.com/watch?v=sqY5LseS4QU",
    "duration": 20,
    "type": "Mixed",
    "target": "Full body",
    "space": "2-5",
    "equipment": "Bodyweight",
    "noise": "Low",
    "difficulty": "Beginner",
    "tags": [
      "Knee / back friendly",
      "Beginner-friendly"
    ],
    "quality": 4,
    "videoId": "sqY5LseS4QU",
    "thumbnail": "https://img.youtube.com/vi/sqY5LseS4QU/mqdefault.jpg"
  },
  {
    "id": 43,
    "platform": "YouTube",
    "author": "Heather Robertson",
    "title": "12 Min HIIT CARDIO — No Equipment, No Repeats",
    "url": "https://www.youtube.com/watch?v=GONKC8Egze4",
    "duration": 12,
    "type": "HIIT",
    "target": "Full body",
    "space": "2-5",
    "equipment": "Bodyweight",
    "noise": "Medium",
    "difficulty": "Intermediate",
    "tags": [],
    "quality": 4,
    "videoId": "GONKC8Egze4",
    "thumbnail": "https://img.youtube.com/vi/GONKC8Egze4/mqdefault.jpg"
  },
  {
    "id": 44,
    "platform": "YouTube",
    "author": "Caroline Girvan",
    "title": "20 Min UNILATERAL DUMBBELL — Single Dumbbell",
    "url": "https://www.youtube.com/watch?v=l9_SoClAO5g",
    "duration": 20,
    "type": "Strength",
    "target": "Full body",
    "space": "2-5",
    "equipment": "Dumbbells",
    "noise": "Low",
    "difficulty": "Advanced",
    "tags": [
      "Hotel-friendly",
      "Low noise"
    ],
    "quality": 5,
    "videoId": "l9_SoClAO5g",
    "thumbnail": "https://img.youtube.com/vi/l9_SoClAO5g/mqdefault.jpg"
  },
  {
    "id": 45,
    "platform": "YouTube",
    "author": "Yoga with Adriene",
    "title": "15 Min Yoga for Flexibility — Deep Stretch",
    "url": "https://www.youtube.com/watch?v=2IcWJobNDck",
    "duration": 15,
    "type": "Mobility",
    "target": "Full body",
    "space": "2-5",
    "equipment": "Yoga mat",
    "noise": "Silent",
    "difficulty": "Beginner",
    "tags": [
      "Beginner-friendly",
      "Knee / back friendly"
    ],
    "quality": 5,
    "videoId": "2IcWJobNDck",
    "thumbnail": "https://img.youtube.com/vi/2IcWJobNDck/mqdefault.jpg"
  },
  {
    "id": 46,
    "platform": "YouTube",
    "author": "GlowBodyPT",
    "title": "15 Min BOOTY BAND WORKOUT — Postpartum Safe",
    "url": "https://www.youtube.com/watch?v=VPwyCCcmYJo",
    "duration": 15,
    "type": "Strength",
    "target": "Legs / glutes",
    "space": "2-5",
    "equipment": "Resistance band",
    "noise": "Low",
    "difficulty": "Beginner",
    "tags": [
      "Postpartum-friendly",
      "Low noise"
    ],
    "quality": 4,
    "videoId": "VPwyCCcmYJo",
    "thumbnail": "https://img.youtube.com/vi/VPwyCCcmYJo/mqdefault.jpg"
  },
  {
    "id": 47,
    "platform": "YouTube",
    "author": "Fitness Blender",
    "title": "25 Min Low Impact Cardio — Bad Knees, No Jumping",
    "url": "https://www.youtube.com/watch?v=8A6Uai5sQVw",
    "duration": 25,
    "type": "Cardio",
    "target": "Full body",
    "space": "2-5",
    "equipment": "Bodyweight",
    "noise": "Low",
    "difficulty": "Beginner",
    "tags": [
      "Beginner-friendly",
      "Knee / back friendly",
      "No jumping"
    ],
    "quality": 4,
    "videoId": "8A6Uai5sQVw",
    "thumbnail": "https://img.youtube.com/vi/8A6Uai5sQVw/mqdefault.jpg"
  },
  {
    "id": 48,
    "platform": "YouTube",
    "author": "MadFit",
    "title": "10 MIN QUIET CARDIO — Hotel Room Friendly",
    "url": "https://www.youtube.com/watch?v=PqqJBaE4srs",
    "duration": 10,
    "type": "Cardio",
    "target": "Full body",
    "space": "<2",
    "equipment": "Bodyweight",
    "noise": "Silent",
    "difficulty": "Beginner",
    "tags": [
      "Low noise",
      "Hotel-friendly",
      "No jumping"
    ],
    "quality": 5,
    "videoId": "PqqJBaE4srs",
    "thumbnail": "https://img.youtube.com/vi/PqqJBaE4srs/mqdefault.jpg"
  },
  {
    "id": 49,
    "platform": "YouTube",
    "author": "Jeff Nippard",
    "title": "12 Min PERFECT Back Workout — Dumbbells Only, Science-Based",
    "url": "https://www.youtube.com/watch?v=12xHxUnBEiI",
    "duration": 12,
    "type": "Strength",
    "target": "Back",
    "space": "2-5",
    "equipment": "Dumbbells",
    "noise": "Low",
    "difficulty": "Intermediate",
    "tags": [],
    "quality": 5,
    "videoId": "12xHxUnBEiI",
    "thumbnail": "https://img.youtube.com/vi/12xHxUnBEiI/mqdefault.jpg"
  },
  {
    "id": 50,
    "platform": "YouTube",
    "author": "Emi Wong",
    "title": "10 Min STANDING ABS — No Equipment",
    "url": "https://www.youtube.com/watch?v=GOlgDBh_h3Q",
    "duration": 10,
    "type": "Strength",
    "target": "Core",
    "space": "<2",
    "equipment": "Bodyweight",
    "noise": "Low",
    "difficulty": "Beginner",
    "tags": [
      "Beginner-friendly",
      "No jumping",
      "Low noise"
    ],
    "quality": 3,
    "videoId": "GOlgDBh_h3Q",
    "thumbnail": "https://img.youtube.com/vi/GOlgDBh_h3Q/mqdefault.jpg"
  },
  {
    "id": 51,
    "platform": "YouTube",
    "author": "Yoga with Adriene",
    "title": "Bedtime Yoga — 20 Minute Bedtime Yoga Practice",
    "url": "https://www.youtube.com/watch?v=v7SN-d4qXx0",
    "duration": 19,
    "type": "Mobility",
    "target": "Full body",
    "space": "<2",
    "equipment": "Yoga mat",
    "noise": "Silent",
    "difficulty": "Beginner",
    "tags": [
      "Low noise",
      "Beginner-friendly"
    ],
    "quality": 5,
    "videoId": "v7SN-d4qXx0",
    "thumbnail": "https://img.youtube.com/vi/v7SN-d4qXx0/mqdefault.jpg"
  },
  {
    "id": 52,
    "platform": "YouTube",
    "author": "Yoga with Adriene",
    "title": "Wind Down Yoga — 12-Minute Bedtime Yoga",
    "url": "https://www.youtube.com/watch?v=BiWDsfZ3zbo",
    "duration": 12,
    "type": "Mobility",
    "target": "Full body",
    "space": "<2",
    "equipment": "Yoga mat",
    "noise": "Silent",
    "difficulty": "Beginner",
    "tags": [
      "Low noise",
      "Beginner-friendly"
    ],
    "quality": 5,
    "videoId": "BiWDsfZ3zbo",
    "thumbnail": "https://img.youtube.com/vi/BiWDsfZ3zbo/mqdefault.jpg"
  },
  {
    "id": 53,
    "platform": "YouTube",
    "author": "Move with Nicole",
    "title": "25 MIN Full Body Pilates Workout for Beginners — No Equipment",
    "url": "https://www.youtube.com/watch?v=NyP_waVgL1w",
    "duration": 27,
    "type": "Mobility",
    "target": "Full body",
    "space": "<2",
    "equipment": "Yoga mat",
    "noise": "Silent",
    "difficulty": "Beginner",
    "tags": [
      "Low noise",
      "Beginner-friendly"
    ],
    "quality": 5,
    "videoId": "NyP_waVgL1w",
    "thumbnail": "https://img.youtube.com/vi/NyP_waVgL1w/mqdefault.jpg"
  },
  {
    "id": 54,
    "platform": "YouTube",
    "author": "Move with Nicole",
    "title": "30 MIN Full Body Workout — At-Home Beginner Pilates",
    "url": "https://www.youtube.com/watch?v=2mkR5LPhOC4",
    "duration": 31,
    "type": "Mobility",
    "target": "Full body",
    "space": "<2",
    "equipment": "Yoga mat",
    "noise": "Silent",
    "difficulty": "Beginner",
    "tags": [
      "Low noise",
      "Beginner-friendly"
    ],
    "quality": 5,
    "videoId": "2mkR5LPhOC4",
    "thumbnail": "https://img.youtube.com/vi/2mkR5LPhOC4/mqdefault.jpg"
  },
  {
    "id": 55,
    "platform": "YouTube",
    "author": "Caroline Girvan",
    "title": "10 Min Dumbbell Upper Body Workout at Home",
    "url": "https://www.youtube.com/watch?v=Mx9RrNZv2TI",
    "duration": 14,
    "type": "Strength",
    "target": "Upper body",
    "space": "2-5",
    "equipment": "Dumbbells",
    "noise": "Low",
    "difficulty": "Intermediate",
    "tags": [
      "Low noise"
    ],
    "quality": 5,
    "videoId": "Mx9RrNZv2TI",
    "thumbnail": "https://img.youtube.com/vi/Mx9RrNZv2TI/mqdefault.jpg"
  },
  {
    "id": 56,
    "platform": "YouTube",
    "author": "Caroline Girvan",
    "title": "20 Minute Arms and Shoulders Workout with Dumbbells",
    "url": "https://www.youtube.com/watch?v=Bl28i6fWljU",
    "duration": 24,
    "type": "Strength",
    "target": "Shoulders",
    "space": "2-5",
    "equipment": "Dumbbells",
    "noise": "Low",
    "difficulty": "Intermediate",
    "tags": [
      "Low noise"
    ],
    "quality": 5,
    "videoId": "Bl28i6fWljU",
    "thumbnail": "https://img.youtube.com/vi/Bl28i6fWljU/mqdefault.jpg"
  },
  {
    "id": 57,
    "platform": "YouTube",
    "author": "Fitness Blender",
    "title": "Fat Burning Low Impact Cardio Workout at Home",
    "url": "https://www.youtube.com/watch?v=waPCCrftvQA",
    "duration": 9,
    "type": "Cardio",
    "target": "Full body",
    "space": "2-5",
    "equipment": "Bodyweight",
    "noise": "Low",
    "difficulty": "Beginner",
    "tags": [
      "No jumping",
      "Low noise",
      "Beginner-friendly",
      "Knee / back friendly"
    ],
    "quality": 5,
    "videoId": "waPCCrftvQA",
    "thumbnail": "https://img.youtube.com/vi/waPCCrftvQA/mqdefault.jpg"
  },
  {
    "id": 58,
    "platform": "YouTube",
    "author": "Fitness Blender",
    "title": "Quiet Cardio Workout — Low Impact No Bounce Recovery Cardio",
    "url": "https://www.youtube.com/watch?v=YaJryQEsT94",
    "duration": 22,
    "type": "Cardio",
    "target": "Full body",
    "space": "2-5",
    "equipment": "Bodyweight",
    "noise": "Silent",
    "difficulty": "Beginner",
    "tags": [
      "No jumping",
      "Low noise",
      "Beginner-friendly",
      "Knee / back friendly"
    ],
    "quality": 5,
    "videoId": "YaJryQEsT94",
    "thumbnail": "https://img.youtube.com/vi/YaJryQEsT94/mqdefault.jpg"
  },
  {
    "id": 59,
    "platform": "YouTube",
    "author": "Grow with Jo",
    "title": "FAST Walking in 15 Minutes — Fat Burning Walk at Home",
    "url": "https://www.youtube.com/watch?v=Nc_NZ3PXhE8",
    "duration": 17,
    "type": "Cardio",
    "target": "Full body",
    "space": "2-5",
    "equipment": "Bodyweight",
    "noise": "Low",
    "difficulty": "Beginner",
    "tags": [
      "No jumping",
      "Low noise",
      "Beginner-friendly"
    ],
    "quality": 5,
    "videoId": "Nc_NZ3PXhE8",
    "thumbnail": "https://img.youtube.com/vi/Nc_NZ3PXhE8/mqdefault.jpg"
  },
  {
    "id": 60,
    "platform": "YouTube",
    "author": "Grow with Jo",
    "title": "FAST 1 Mile Walk at Home — Happy Mood Boost",
    "url": "https://www.youtube.com/watch?v=_bq49gbCyPw",
    "duration": 17,
    "type": "Cardio",
    "target": "Full body",
    "space": "2-5",
    "equipment": "Bodyweight",
    "noise": "Low",
    "difficulty": "Beginner",
    "tags": [
      "No jumping",
      "Low noise",
      "Beginner-friendly"
    ],
    "quality": 5,
    "videoId": "_bq49gbCyPw",
    "thumbnail": "https://img.youtube.com/vi/_bq49gbCyPw/mqdefault.jpg"
  },
  {
    "id": 61,
    "platform": "YouTube",
    "author": "MIZI",
    "title": "20 MIN Toned Upper Body Dumbbell Workout — Arms, Back, Abs",
    "url": "https://www.youtube.com/watch?v=92fq0hCa2PY",
    "duration": 23,
    "type": "Strength",
    "target": "Upper body",
    "space": "2-5",
    "equipment": "Dumbbells",
    "noise": "Low",
    "difficulty": "Intermediate",
    "tags": [
      "Low noise"
    ],
    "quality": 5,
    "videoId": "92fq0hCa2PY",
    "thumbnail": "https://img.youtube.com/vi/92fq0hCa2PY/mqdefault.jpg"
  },
  {
    "id": 62,
    "platform": "YouTube",
    "author": "MIZI",
    "title": "15-Min Upper Body Dumbbell Blast — Arms, Shoulders, Chest & Back",
    "url": "https://www.youtube.com/watch?v=e95hJapyXZE",
    "duration": 17,
    "type": "Strength",
    "target": "Upper body",
    "space": "2-5",
    "equipment": "Dumbbells",
    "noise": "Low",
    "difficulty": "Intermediate",
    "tags": [
      "Low noise"
    ],
    "quality": 5,
    "videoId": "e95hJapyXZE",
    "thumbnail": "https://img.youtube.com/vi/e95hJapyXZE/mqdefault.jpg"
  },
  {
    "id": 63,
    "platform": "YouTube",
    "author": "Sydney Cummings",
    "title": "30 Minute Full Body Dumbbell Strength Workout",
    "url": "https://www.youtube.com/watch?v=ONRx-FUKPZs",
    "duration": 33,
    "type": "Strength",
    "target": "Full body",
    "space": "2-5",
    "equipment": "Dumbbells",
    "noise": "Low",
    "difficulty": "Intermediate",
    "tags": [
      "Low noise"
    ],
    "quality": 4,
    "videoId": "ONRx-FUKPZs",
    "thumbnail": "https://img.youtube.com/vi/ONRx-FUKPZs/mqdefault.jpg"
  },
  {
    "id": 64,
    "platform": "YouTube",
    "author": "Sydney Cummings",
    "title": "15 Minute Full Body Dumbbell Workout",
    "url": "https://www.youtube.com/watch?v=X0r4YZGBU7I",
    "duration": 17,
    "type": "Strength",
    "target": "Full body",
    "space": "2-5",
    "equipment": "Dumbbells",
    "noise": "Low",
    "difficulty": "Intermediate",
    "tags": [
      "Low noise"
    ],
    "quality": 4,
    "videoId": "X0r4YZGBU7I",
    "thumbnail": "https://img.youtube.com/vi/X0r4YZGBU7I/mqdefault.jpg"
  },
  {
    "id": 65,
    "platform": "YouTube",
    "author": "HASfit",
    "title": "15 Min Beginners HIIT Workout — Standing No Jumping",
    "url": "https://www.youtube.com/watch?v=6LhBEg-siIA",
    "duration": 18,
    "type": "HIIT",
    "target": "Full body",
    "space": "2-5",
    "equipment": "Bodyweight",
    "noise": "Low",
    "difficulty": "Beginner",
    "tags": [
      "No jumping",
      "Low noise",
      "Beginner-friendly"
    ],
    "quality": 4,
    "videoId": "6LhBEg-siIA",
    "thumbnail": "https://img.youtube.com/vi/6LhBEg-siIA/mqdefault.jpg"
  },
  {
    "id": 66,
    "platform": "YouTube",
    "author": "HASfit",
    "title": "20 Min HIIT Workout for Beginners — No Jumping No Equipment",
    "url": "https://www.youtube.com/watch?v=HRKLiX_7BZA",
    "duration": 22,
    "type": "HIIT",
    "target": "Full body",
    "space": "2-5",
    "equipment": "Bodyweight",
    "noise": "Low",
    "difficulty": "Beginner",
    "tags": [
      "No jumping",
      "Low noise",
      "Beginner-friendly"
    ],
    "quality": 4,
    "videoId": "HRKLiX_7BZA",
    "thumbnail": "https://img.youtube.com/vi/HRKLiX_7BZA/mqdefault.jpg"
  }
]
;
